-- CREATE TABLE players (
--     id INTEGER PRIMARY KEY, 
--     name TEXT UNIQUE 
-- );

-- CREATE TABLE games (
--     id Integer Primary KEY,
--     player_id INTEGER,
--     player_choice TEXT,
--     computer_choice TEXT,
--     outcome TEXT,
--     FOREIGN KEY (player_id) REFERENCES players (id)
-- );
